apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ulilnn64t-python
  janus-idp.io/tekton: ulilnn64t-python
  backstage.io/kubernetes-id: ulilnn64t-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ulilnn64t-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
